### ISSUE TITLE
Human readable fixture description to list of fixtures to load

### ISSUE THREAD

**Issue by MLKiiwy** [lafourchette/FixturesBundle#16]
New feature, provide a way to use a clear human readable description. 

By exemple : 
"I have an man user called 'Henry' with two child Beth and Andy."

In a configuration file we have : 
```yml
fixtures:
    sentences:
        "I have an man user called 'Henry' with two child Beth and Andy.":
                - @MyBundle/fixtures/user.yml              
                - @MyBundle/fixtures/child.yml
```

If I call the loader with these sentence : 
$loader->loadBySentence("I have an man user called 'Henry' with two child Beth and Andy.")
The file user and child will be loaded with include fixtures.

Also all features of bundle (groups, dependencies, set) will be applied in the loader so it's easy to create a lot of human reading sentence to describe your fixtures and combinate them.
